# Generated by Django 5.0.6 on 2024-05-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainrequest',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
