# Generated by Django 5.0.6 on 2024-05-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_complainrequest_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainrequest',
            old_name='image',
            new_name='files',
        ),
    ]
