# Generated by Django 5.0.6 on 2024-05-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_image_complainrequest_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
